CREATE TABLE guia (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Datos que vienen de SAP. doc_entry identifica el documento alla y es lo que
    -- usa la sincronizacion para no importar dos veces la misma guia.
    doc_entry                   INTEGER      NOT NULL,
    folio                       BIGINT       NOT NULL,
    cliente                     VARCHAR(255) NOT NULL,
    direccion                   VARCHAR(255) NOT NULL,

    -- Datos que genera la app. Nacen vacios: una guia recien importada todavia no
    -- tiene repartidor, ni fecha de entrega, ni evidencia. Por eso admiten NULL.
    repartidor_id               INTEGER,
    recibida_por_repartidor     BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha_recepcion_repartidor  TIMESTAMP WITH TIME ZONE,
    -- VARCHAR y no un entero: el enum se persiste con @Enumerated(EnumType.STRING),
    -- asi reordenar EstadoGuia no corrompe las filas ya guardadas.
    estado                      VARCHAR(20)  NOT NULL,
    fecha_entrega               TIMESTAMP WITH TIME ZONE,

    -- Evidencia fotografica. El hash es SHA-256 en hexadecimal: 64 caracteres fijos.
    -- No viaja a SAP; es lo que prueba que la foto no se altero despues de capturada.
    url_foto                    VARCHAR(500),
    hash_foto                   VARCHAR(64),

    sincronizada                BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_guia            PRIMARY KEY (id),
    CONSTRAINT uq_guia_doc_entry  UNIQUE (doc_entry)
);

-- Sostienen findByRepartidorId y findByEstado, las dos consultas que corren en cada
-- carga de pantalla (la app del repartidor y el panel de oficina).
CREATE INDEX ix_guia_repartidor_id ON guia (repartidor_id);
CREATE INDEX ix_guia_estado        ON guia (estado);
