-- Datos que necesita la optimizacion de rutas.

-- Comments de la guia en SAP. Ahi el vendedor suele dejar el horario de recepcion.
ALTER TABLE guia ADD COLUMN comentario VARCHAR(500);

-- Coordenadas de la direccion de despacho. Se geocodifican una sola vez y se borran
-- si SAP corrige la direccion, para que se vuelvan a calcular.
ALTER TABLE guia ADD COLUMN latitud DOUBLE PRECISION;
ALTER TABLE guia ADD COLUMN longitud DOUBLE PRECISION;
-- Google no encontro la direccion exacta, solo la calle o la comuna: el repartidor
-- tiene que confirmarla antes de salir.
ALTER TABLE guia ADD COLUMN ubicacion_aproximada BOOLEAN NOT NULL DEFAULT FALSE;

-- Horario de recepcion. Lo define el bodeguero o sale de interpretar el comentario;
-- origen_horario dice cual. NULL = todavia no se interpreto el comentario.
ALTER TABLE guia ADD COLUMN ventana_desde TIME;
ALTER TABLE guia ADD COLUMN ventana_hasta TIME;
ALTER TABLE guia ADD COLUMN nota_entrega VARCHAR(500);
ALTER TABLE guia ADD COLUMN origen_horario VARCHAR(20);

-- Una ruta por repartidor y dia: regenerarla reemplaza la anterior.
CREATE TABLE ruta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    repartidor_id   INTEGER                  NOT NULL,
    fecha           DATE                     NOT NULL,
    hora_salida     TIME                     NOT NULL,
    generada_en     TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_ruta                     PRIMARY KEY (id),
    CONSTRAINT uq_ruta_repartidor_fecha    UNIQUE (repartidor_id, fecha)
);

CREATE TABLE ruta_parada (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ruta_id           BIGINT                   NOT NULL,
    guia_id           BIGINT                   NOT NULL,
    orden             INTEGER                  NOT NULL,
    llegada_estimada  TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_ruta_parada       PRIMARY KEY (id),
    CONSTRAINT fk_ruta_parada_ruta  FOREIGN KEY (ruta_id) REFERENCES ruta (id) ON DELETE CASCADE,
    CONSTRAINT fk_ruta_parada_guia  FOREIGN KEY (guia_id) REFERENCES guia (id),
    -- Una guia va en una sola ruta: reasignarla la saca de la anterior.
    CONSTRAINT uq_ruta_parada_guia  UNIQUE (guia_id)
);

CREATE INDEX ix_ruta_parada_ruta_id ON ruta_parada (ruta_id);
